apiVersion: apps/v1
kind: Deployment
metadata:
  name: kungfu-panda
  namespace: confucio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kungfu-panda
  template:
    metadata:
      labels:
        app: kungfu-panda
    spec:
      containers:
        - name: container
          image: httpd:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 600