apiVersion: apps/v1
kind: Deployment
metadata:
  name: casper
  namespace: ghosts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: casper
  template:
    metadata:
      labels:
        app: casper
    spec:
      containers:
        - name: container
          image: httpd:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 600