apiVersion: v1
kind: ServiceAccount
metadata:
  name: comanche-sa
  namespace: ghosts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tribu
  namespace: comanche
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tribu
  template:
    metadata:
      labels:
        app: tribu
    spec:
      serviceAccountName: comanche-sa
      containers:
        - name: apache
          image: httpd:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 600